version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: game_hub_test_postgres
    environment:
      POSTGRES_DB: game_hub_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"  # 기본 포트와 충돌 방지를 위해 5433 사용
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./database/init-test.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d game_hub_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
